# serverless.yml
# dashboard.cccouncilpublicwebsite.aws.zoetebier.net

service: dashboard
app: cccouncil
org: johnzoet

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-southeast-2

  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource:            
            - { "Fn::GetAtt": ["trafficStats", "Arn" ] }

  environment:
    DYNAMODB_TABLE: trafficStats

package:
  exclude:
    - node_modules/**
    - backend/frontend/**
    - backend/venv/**
    - backend/.vscode/**
    - backend/__pycache__/**
    - backend/.dynamodb/**
    - ops/**    
    - .serverless/**
    - package-lock.json
    - .DS_Store

functions:
  getTrafficStat:
    handler: backend/get_traffic_stat.handler
    events:
      - http:
          path: stats
          method: get
          cors: true

resources:
  Resources:
    trafficStats:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: statName
            AttributeType: S
        KeySchema:
          - AttributeName: statName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  client:
    bucketName: dashboard.cccouncilpublicwebsite.aws.zoetebier.net
    distributionFolder: frontend
    indexDocument: index.html
    errorDocument: error.html

plugins:
  - serverless-finch
